import {
  Atom,
  Braces,
  CheckCircle,
  ClipboardList,
  Cloud,
  Code,
  Cpu,
  Database,
  FileText,
  Flame,
  Github,
  Hexagon,
  Layers,
  Layout,
  Palette,
  Plug,
  Search,
  Server,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Wrench,
  Workflow,
  Zap,
  type LucideIcon,
} from 'lucide-react';

const map: Record<string, LucideIcon> = {
  atom: Atom,
  braces: Braces,
  'check-circle': CheckCircle,
  'clipboard-list': ClipboardList,
  cloud: Cloud,
  code: Code,
  cpu: Cpu,
  database: Database,
  'file-text': FileText,
  flame: Flame,
  framework: Layers,
  github: Github,
  hexagon: Hexagon,
  layers: Layers,
  layout: Layout,
  palette: Palette,
  plug: Plug,
  search: Search,
  server: Server,
  shield: Shield,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  smartphone: Smartphone,
  sparkles: Sparkles,
  wrench: Wrench,
  workflow: Workflow,
  zap: Zap,
};

export function getIcon(name: string): LucideIcon {
  return map[name] ?? Sparkles;
}
